feature:
  - any: [ 'src/*.ts','src/**/*.ts', '!src/docs/*' ]

test:
  - 'src/factory/*.test.ts'
  - 'src/store/**/*.test.ts'
  - 'src/**/*.spec.ts'
  - 'src/*.test.ts'

ci-update:
  - any: [ '.github/**/*.yml','.github/*.yml', 'configs/*.json']

dependencies:
  - any: [ 'package.json', 'yarn.lock' ]

documentation:
  - any: [ 'README.md' ]

