feature:
  - any: [ 'src/*.ts','src/**/*.ts', '!src/docs/*' ]

fix:
  - any: [ 'src/*.ts', 'src/**/*.ts', '!src/docs/*' ]

test:
  - any: [ 'src/**/*.test.ts','src/**/*.spec.ts','src/*.test.ts' ]

ci-update:
  - any: [ '.github/**/*','.github/*', 'configs/*' ]

dependencies:
  - any: [ 'package.json', 'yarn.lock' ]

documentation:
  - any: [ 'README.md' ]

