name: Build Test

on:
  push:
    paths-ignore:
      - '**/node_modules/**'
      - '.github/**'
    branches:
      - master
  pull_request:
    branches-ignore:
      - renovate*
      - feature/*
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - name: Run __tests__ (coverage)
        run: |
          yarn rebuild
          export FORCE_COLOR=true
          export TEST_MNEMONIC=${{ secrets.TEST_MNEMONIC }}
          yarn test:integration --coverage
