name: Build Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - name: Run __tests__ (coverage)
        run: |
          export FORCE_COLOR=true
          yarn test:integration --coverage
