name: 'coverage'
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ArtiomTr/jest-coverage-report-action@v2.0.6
        with:
          package-manager: yarn
          skip-step: all
