name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
