name: Release on Tag

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Build project
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - uses: actions/cache@v3.0.2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: build
        run: |
          yarn
          yarn build

      - name: publish
        run: |
          yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/tags/')
