name: Release on Tag

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Build project
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - uses: actions/cache@
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: build
        run: |
          yarn
          yarn build

      - id: publish
        run:
          yarn publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/tags/')
